<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Todo') ?></h3>
            </div>
            <div class="panel-body">
            </div>
            <p>
                <ul>
                    <li>1. Créer une interface permettant de saisir un nouvel utilisateur (Prénom, Nom, email, password, date de naissance, date de création, date de modification)</li>
                    <li>2. Créer une interface que liste les utilisateurs</li>
                    <li>3. Ajouter les interfaces de modification d'un utilisateur</li>
                    <li>4. Ajouter la supression d'un utilisateur</li>
                    <li>5. Intégrer elasticsearch à l'application de sorte à indexer les utilisateurs dans Elastic search (ES)</li>
                    <li>6. Surcharger les sélection d'utilisteur pour utiliser ES au lieu de la base de données</li>
                </ul>
            </p>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Conseils') ?></h3>
            </div>
            <div class="panel-body">
            </div>
            <p>
            <ul>
                <li>Respecter le PSR-2 (vérification avec codesniffer)</li>
                <li>Ecrire les test unitaire sur au moins les entités de l'application</li>
                <li>Intégrer elasticsearch une fois l'application développée à l'aide du gestionnaire d'évènement de ZF2</li>
            </ul>
            </p>
        </div>
    </div>
</div>
